version: "3.7"
services:
  web1:
    container_name: web1
    build:
      context: .
      dockerfile: docs/docker/web1.Dockerfile
    depends_on:
      - serv1
  web2:
    container_name: web2
    build:
      context: .
      dockerfile: docs/docker/web1.Dockerfile
    depends_on:
      - serv1
  serv1:
    container_name: serv1
    build:
      context: .
      dockerfile: docs/docker/serv1.Dockerfile
  service_balancer:
    container_name: service_balancer
    build:
      context: .
      dockerfile: service_haproxy/haproxy.Dockerfile
    ports:
      - 84:84
      - 83:83
    depends_on:
      - web1
 
